version: '3.8'
services:
   
  spring:
    build:
      context: .
      dockerfile: DockerFile
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    

  db:
    image: mysql:8.0
    ports:
      - 33060:33060
    restart: always
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    
